version: "3"
services:
  geosm_carto:
    build:
      context: .
      dockerfile: .docker/Dockerfile
    image: geosm_carto
    container_name: geosm_carto
    restart: unless-stopped
    tty: true
    volumes:
      - 'carto-data:/var/www/html'
    ports:
      - "9090:80"

volumes:
    carto-data:
        driver: local
    